### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by fingerpich** [microsoft/TypeScript-Node-Starter#349]
node_modules/mongoose/node_modules/@types/mongodb/index.d.ts:58:111 - error TS7016: Could not find a declaration file for module 'bson'. '/Users/fingerpich/Documents/projects/deyorg/backend/node_modules/bson/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/bson` if it exists or add a new declaration (.d.ts) file containing `declare module 'bson';`

**Comment by fingerpich** [comment]
Fixed the problem by `npm i bson`

**Comment by peterblazejewicz** [comment]
thx! just a note, there was a lot of changes in DT ecosystem for mongo/mongoose, including packages going native TS, not using definition files anymore, so there could be a problem sometimes when resolving dependencies for some deps, like here in this project.

**Comment by mozgbrasil** [comment]
Good morning my friends

I installed the dependency here but the error persists, can you help me

Thanks in advance to everyone who can contribute.

![Captura de tela de 2022-02-08 16-41-34](https://user-images.githubusercontent.com/17202780/153063215-0d4b7617-a15b-443a-b62f-c98988dfbf85.png)
![Captura de tela de 2022-02-08 16-41-41](https://user-images.githubusercontent.com/17202780/153063220-62f24758-7acb-444d-adae-1afb6c0aa355.png)

**Comment by peterblazejewicz** [comment]
@mozgbrasil I've merged fixes tested on Debian with Yarn 1.22.*.
This project is not very actively developed so some of the dependencies were resolved differently and missing actual types, when Yarn was used as the package manager. I've added fixed versions matching this project setup and made this project compatible with Node v14 or newer. 
Thanks!
